---
# In order to run the node_exporter daemon,
# you can run:
# launchctl load /Library/LaunchDaemons/org.mongodb.node_exporter.plist
# to stop the daemon, you can run:
# launchctl unload /Library/LaunchDaemons/org.mongodb.node_exporter.plist
# to list running services, you can run:
# launchctl list
- name: Copy over node_exporter plist file
  become: true
  template:
    src: org.mongodb.node_exporter.plist.j2
    dest: "{{ node_exporter_plist_dest }}"
    owner: root
    group: wheel
    mode: 0600

- name: Check if node_exporter daemon is running
  become: true
  shell: launchctl list | grep {{ node_exporter_plist_label }}
  changed_when: false
  ignore_errors: true
  register: launchctl_list

- name: Start node_exporter daemon
  become: true
  command: launchctl load {{ node_exporter_plist_dest }}
  when: launchctl_list is not succeeded
