---
- name: Copy over systemd template for node_exporter
  become: true
  template:
    src: node_exporter.service.j2
    dest: "{{ node_exporter_service_file_dest }}/{{ node_exporter_service_name }}.service"
    owner: root
    group: root
    mode: 0600

- name: Enable node_exporter
  become: true
  systemd:
    enabled: true
    state: started
    name: "{{ node_exporter_service_name }}"
