---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-node-exporter"
      include_role:
        name: "ansible-role-node-exporter"
      vars:
        node_exporter_version: 1.0.0-rc.0
        node_exporter_service_file_dest: /etc/systemd/system/
