---
- name: Converge systemd hosts
  hosts: all
  tasks:
    - name: Run converge on systemd hosts
      block:
        - name: "Include ansible-role-node-exporter"
          include_role:
            name: "ansible-role-node-exporter"
          vars:
            node_exporter_final_dest: /tmp/node_exporter_test
            node_exporter_listen_port: 9101
            node_exporter_service_file_dest: /etc/systemd/system/
            node_exporter_service_name: node_exporter_test
            node_exporter_version: 1.0.0-rc.0
      when: ansible_service_mgr == "systemd"

- name: Converge upstart hosts
  hosts: all
  tasks:
    - name: Run converge on upstart hosts
      block:
        - name: "Include ansible-role-node-exporter"
          include_role:
            name: "ansible-role-node-exporter"
          vars:
            node_exporter_final_dest: /tmp/node_exporter_test
            node_exporter_listen_port: 9101
            node_exporter_service_file_dest: /etc/rc.d/init.d/
            node_exporter_service_name: node_exporter_test
            node_exporter_version: 1.0.0-rc.0
      when: ansible_service_mgr == "upstart"

- name: Converge macos-1014
  hosts: macos-1014
  tasks:
    - name: "Include ansible-role-node-exporter"
      include_role:
        name: "ansible-role-node-exporter"
      vars:
        node_exporter_final_dest: /tmp/node_exporter_test
        node_exporter_version: 1.0.0-rc.0
        node_exporter_listen_port: 9101
        node_exporter_service_name: node_exporter_test
        node_exporter_service_file_dest: /Library/LaunchDaemons/org.mongodb.node_exporter_test.plist
