---
- name: Destroy macos-1014
  hosts: macos-1014
  tasks:
    - name: Check if node_exporter daemon is running
      become: true
      shell: launchctl list | grep node_exporter_test
      changed_when: false
      ignore_errors: true
      register: launchctl_list

    - name: Stop node exporter test daemon
      become: true
      command: launchctl unload /Library/LaunchDaemons/org.mongodb.node_exporter_test.plist
      when: launchctl_list is succeeded

    - name: Remove test node exporter plist file
      become: true
      file:
        path: /Library/LaunchDaemons/org.mongodb.node_exporter_test.plist
        state: absent

- name: Destroy systemd hosts
  hosts: all
  tasks:
    - name: Run destroy tasks on systemd services
      block:
        - name: Check if node_exporter service exists
          service_facts:

        - name: Stop node_exporter service
          become: true
          systemd:
            name: node_exporter_test
            state: stopped
            enabled: false
          when: services["node_exporter_test.service"] is defined

        - name: Delete test files
          become: true
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/systemd/system/node_exporter_test.service
      when: ansible_service_mgr == "systemd"

- name: Destroy upstart hosts
  hosts: all
  tasks:
    - name: Run destroy tasks on upstart services
      block:
        - name: Check if node_exporter_test service is running  # noqa 303
          command: service node_exporter_test status
          changed_when: false
          ignore_errors: true
          register: node_exporter_status

        - name: Stop node_exporter service
          become: true
          service:
            name: node_exporter_test
            state: stopped
          when: node_exporter_status.rc == 0

        - name: Delete test files
          become: true
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/rc.d/init.d/node_exporter_test
      when: ansible_service_mgr == "upstart"

- name: Destroy
  hosts: all
  tasks:
    - name: Delete node exporter test directory
      file:
        path: /tmp/node_exporter_test
        state: absent
