---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  #- name: macos-1014
  - name: rhel81-power8
  - name: rhel80-s390x
  - name: suse15-s390x
  - name: ubuntu1604-ppc64le
  - name: ubuntu1804-s390x
  - name: ubuntu1804-ppc64le
provisioner:
  name: ansible
  inventory:
    host_vars:
      macos-1014:
        ansible_python_interpreter: "/usr/bin/python"
verifier:
  name: testinfra
