---
env:
  REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME }}
  REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD }}
jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up private key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up ssh config
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        run: |
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          chmod 600 ~/.ssh/config
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - name: Log into RedHat
        uses: azure/docker-login@v1
        with:
          login-server: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_SERVICE_ACCOUNT_PASSWORD }}
      - run: molecule test
      - run: molecule test -s static-hosts
name: Molecule Test
'on':
  - push
